# MySQL
spring:
  datasource:
    hikari:
      driver-class-name: "com.mysql.cj.jdbc.Driver"
      auto-commit: true
      connection-timeout: 2000
      idle-timeout: 2000
      maximum-pool-size: 255
      minimum-idle: 5
      max-lifetime: "1000000"
    type: "com.zaxxer.hikari.HikariDataSource"
#    url: "jdbc:mysql://localhost:3306/qzy_task_manager?useSSL=false&useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=25&prepStmtCacheSqlLimit=256&nullNamePatternMatchesAll=true"
    url: "jdbc:mysql://10.66.236.132:3306/qzy_file_store?useSSL=false&useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=25&prepStmtCacheSqlLimit=256&nullNamePatternMatchesAll=true"
    username: "root"
    password: "y9e39*@)UJ=1"
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: "root"
#    password: ""
  jooq:
      sql-dialect: mysql
  freemarker:
    settings:
      exception_on_missing_template: true
server:
  port: 8090
wcs:
  conf:
    ak: "0a3836b4ef298e7dc9fc5da291252fc4ac3e0c7f"
    sk: "da17a6ffaeab4ca89ce7275d9a8060206cb3de8e"
    mdomain: "qietv.up21.v1.wcsapi.com"
    udomain: "upload-vod-v1.qiecdn.com"
#    password: "dkmepNSo)W@9_="
#    username: "cdb_outerroot"